### ISSUE TITLE
linkWith() does not work on React Native 0.61+

### ISSUE THREAD

**Issue by MileanCo** [parse-community/Parse-SDK-JS#1126]
Example usage - 
```
import Parse from 'parse/react-native';
Parse.setAsyncStorage(AsyncStorage);
const user = new Parse.User();
const auth_data_spotify = {
                id:results_me.body.id,
                access_token:spotify_access_token,
};
user.linkWith('spotify', { authData: auth_data_spotify })
```

```
Cannot call currentUser() when using a platform with an async storage system. Call currentUserAsync() instead.
- node_modules/parse/lib/react-native/ParseUser.js:1087:8 in DefaultController.currentUser
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:175300:38 in current
- node_modules/parse/lib/react-native/ParseUser.js:356:2 in isCurrent
- node_modules/parse/lib/react-native/ParseUser.js:553:11 in save
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

```

### Environment Setup
"expo": "^36.0.0",
"parse": "^2.11.0",
"react": "^16.9.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",

**Comment by dplewis** [comment]
This has been addressed and will be included in the next release

**Comment by MileanCo** [comment]
Any idea when the next version will be released? I used the master branch of Parse JS SDK from here instead of 2.11 from npm, but I still get this error...

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/1128

@MileanCo Can you try the latest release. Let us know if your issue persists

**Comment by MileanCo** [comment]
The issue is still there :( 
It happens after doing this:
```
const user = new Parse.User();
user.linkWith() // crash
```

```

Cannot call currentUser() when using a platform with an async storage system. Call currentUserAsync() instead.
- node_modules/parse/lib/react-native/ParseUser.js:769:17 in DefaultController.currentUser
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:175369:38 in value
- node_modules/parse/lib/react-native/ParseUser.js:302:23 in value
- node_modules/parse/lib/react-native/ParseUser.js:411:23 in value
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
```

**Comment by MileanCo** [comment]
I also get some weird warning about Linking requires a scheme when the app loads. I dont think this is related to the above issue though...
```
Linking requires that you provide a `scheme` in app.json for standalone apps - if it is left blank, your app may crash. The scheme does not apply to development in the Expo client but you should add it as soon as you start working with Linking to avoid creating a broken build. Add a `scheme` to silence this warning. Learn more about Linking at https://docs.expo.io/versions/latest/workflow/linking/
- node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
- node_modules/expo/build/Linking/Linking.js:40:13 in makeUrl
- node_modules/expo/build/AuthSession.js:78:31 in getDefaultReturnUrl
- node_modules/expo/build/AuthSession.js:7:0 in startAsync

```

**Comment by dplewis** [comment]
@MileanCo Can you debug

`- node_modules/parse/lib/react-native/ParseUser.js:302:23`
`- node_modules/parse/lib/react-native/ParseUser.js:769:17 in DefaultController.currentUser`

You can compare it with this SDK. Under the hood linkWith should be using currentUserAsync unless you are also doing Parse.User.current();

**Comment by MileanCo** [comment]
ParseUser.js:302 is this line https://github.com/parse-community/Parse-SDK-JS/blob/7f32cd53daf0a1e3eb045050d2adbaa14a617afa/src/ParseUser.js#L295 

ParseUser.js:769 is this code https://github.com/parse-community/Parse-SDK-JS/blob/7f32cd53daf0a1e3eb045050d2adbaa14a617afa/src/ParseUser.js#L914

I dont call Parse.User.current() anywhere and im using parse@2.12.0

**Comment by dplewis** [comment]
You are using isCurrent() which calls Parse.User.current() `ParseUser.current()`

We could create another function isCurrentAsync or change it internally.

**Comment by MileanCo** [comment]
No where in my code am I calling isCurrent(). Here are all the references to Parse in my code... The stack trace is originally coming from some flushQueue, meaning that work was created through some other code calling isCurrent. I have this same (or very similar) code in another project using the latest Parse code and React Native 0.59 (Expo SDK 35) and it works there...

```
bash$ grep Parse * -r
App.js:import Parse from 'parse/react-native.js';
App.js:Parse.setAsyncStorage(AsyncStorage);
App.js:Parse.initialize(PARSE_APP_ID);
App.js:Parse.serverURL = PARSE_HOST_URL;
api/store/actions/userActions.js:import Parse from 'parse/react-native.js';
api/store/actions/userActions.js:            const user = new Parse.User();

```

**Comment by dplewis** [comment]
If you could create a separate project that can reproduce this issue and post it that would help debug this issue.

**Comment by anitricks** [comment]
Im having the same issue with v2.12.0 (latest version) using ```linkWith``` for any social provider. I am not calling Parse.user.current() anywhere in my code and have set the async storage before any calls are made

**Comment by eberperetto** [comment]
Hey! I'm having the same issue using v2.19.0 and RN v0.63.4 while trying to call `linkWith` with a Google provider. [Here](https://github.com/eberperetto/ParseSDKJSlinkWithIssue) is a separate project reproducing this issue with batteries included.
Thanks!

**Comment by dplewis** [comment]
@eberperetto Thanks for creating the project. I appreciated it. Can you open a separate issue so this conversation doesn't get lost?
