### ISSUE TITLE
The package at "node_modules\parse\lib\react-native\ParseFile.js" attempted to import the Node standard library module "http"

### ISSUE THREAD

**Issue by murshudov** [parse-community/Parse-SDK-JS#768]
### Issue Description

Seems like version 2.3.0 uses Node standart http module and it breaks compatibility with React-Native. Version 2.2.1 uses CoreManager for http requests

### Steps to reproduce

Try to run react-native project which uses Parse JS SDK version 2.3.0

### Expected Results

Everything should be fine

### Actual Outcome

Crash with exception:

The package at "node_modules\parse\lib\react-native\ParseFile.js" attempted to import the Node standard library module "http"

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.1.3
  - Operating System:     Windows 10
  - Hardware:             Dell XPS 15
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **JS SDK**
  - JS SDK version: 2.3.0
  - Application? (Browser, Node, React-Native, etc): React-Native

**Comment by dplewis** [comment]
This has been fixed https://github.com/parse-community/Parse-SDK-JS/pull/765 and will be released in 2.3.1

**Comment by funjay** [comment]
funny this is still happening in 2025? did nobody experience this after this ?

**Comment by mtrezza** [comment]
@funjay This issue is closed. If you experience any issues please open a new GitHub issue and reference this one if applicable.
